size:
  length_max_255: 255
  length_max_name: 100
  min_password: 6
  text_2000: 2000
number:
  cate: 90
  tour: 42.41
  booking: 760
  view: 2000
tours:
  per_page: 9
  show_name: 30
  show_description: 40
  show_location: 10
  image_demo_lg: "http://placehold.it/1200x300"
  image_demo: "http://placehold.it/400x250/000/fff"
  price_row: 2
